### ISSUE TITLE
Width needs to be made bigger

### ISSUE THREAD

**Issue by yakov116** [tanmayrajani/notifications-preview-github#102]
Since the mark as read has been restored I find myself accidentally clicking the "read" checkbox

**Comment by silverwind** [comment]
I think it's wide enough already, especially on small screens.

**Comment by tanmayrajani** [comment]
Yes, I think so too. I mean, it's "compact" mode for a reason. If you want more width, you can always go back to non-compact mode using the options.

Still, if more people think we should increase the width, I'd be happy to.

**Comment by silverwind** [comment]
What could be done is a minimum or fixed width instead of completely dynamic as it is now. For example currently the hover effect cuts into small items a bit too much:

<img src="https://user-images.githubusercontent.com/115237/89097306-2f6b8f00-d3de-11ea-90fd-079f6310b4c1.png" width="400"/>

After adding a minimum width like:

```css
.NPG-dropdown .notifications-list-item {
  min-width: 400px;
}
````

<img src="https://user-images.githubusercontent.com/115237/89097348-7b1e3880-d3de-11ea-84d9-ef490ce03ad8.png" width="400"/>
