### ISSUE TITLE
Finish transition to new Notifications

### ISSUE THREAD

**Issue by fregante** [tanmayrajani/notifications-preview-github#89]
#81 added support for the new Notifications in the least intrusive way possible, but the CSS is almost entirely outdated and the JS still has some references to DOM that no longer exists.

- [ ] Fix mark as read: https://github.com/tanmayrajani/notifications-preview-github/issues/93
- [x] Improve style
- [x] Drop unused CSS
- [x] Fix non-Compact view (currently unsupported)
- [x] Drop outdated JS

#57 could be considered

**Comment by darkred** [comment]
I've noticed the following with the new version, regarding the #57 feature:
<sup>and thought to post it here, instead of opening a new issue</sup> 

*(Tested extension 20.4.5 in a fresh Chrome 81 profile)*
if I enable `Show only participating notifications` then the notification number in the bubble is no longer displayed, even if `Show notification number in blue bubble` remains enabled.

Screenshots having `Show only participating notifications` :


<details>
<summary>Enabled</summary>

![2020-04-09_121059](https://user-images.githubusercontent.com/723651/78880360-f63d9680-7a5d-11ea-9edd-1d602fb058e0.jpg)

</details>

<details>
<summary>Disabled</summary>

![2020-04-09_121150](https://user-images.githubusercontent.com/723651/78881010-e2defb00-7a5e-11ea-8c17-980f72aae488.jpg)

</details>

**Comment by fregante** [comment]
Please open a new issue if it's still broken. I'll mark this as done due to https://github.com/tanmayrajani/notifications-preview-github/releases/tag/20.4.22

**Comment by fregante** [comment]
If you enable GitHub’s "Group by repository" option, the extension now exactly looks like it used to 🎉 

<img width="196" alt="option" src="https://user-images.githubusercontent.com/1402241/80043463-0e072700-8502-11ea-8aa1-df13a868f680.png">

<img width="585" alt="grouped" src="https://user-images.githubusercontent.com/1402241/80043466-119aae00-8502-11ea-83c5-62fe6b084704.png">

While the new style is this, cleaned up:

<img width="595" alt="ungrouped" src="https://user-images.githubusercontent.com/1402241/80043474-14959e80-8502-11ea-9f03-bbeec793e479.png">

**Comment by darkred** [comment]
> Please open a new issue if it's still broken. I'll mark this as done due to [`20.4.22` (release)](https://github.com/tanmayrajani/notifications-preview-github/releases/tag/20.4.22)

I see that the new version, 20.4.22, is available only in Firefox AMO.
In CWS it's still 20.4.5. Maybe it's stuck at pending review ?? 

And, I've tested the Firefox version, and the counter in the bubble is still broken if I enable `Show only participating notifications`. Is it ok if I open a new issue based only on the Firefox version?

**Comment by fregante** [comment]
This is due to #91

**Comment by darkred** [comment]
Thanks for the info. 
The review procedure in CWS is still so awful for the developers..

**Comment by fregante** [comment]
They started requesting more information lately, so every old extension is stuck until we add the information. It happened to my other 3 extensions I updated recently.

**Comment by darkred** [comment]
Thank you for the quick response. 
I opened a new issue here: https://github.com/tanmayrajani/notifications-preview-github/issues/95
